server:
    port: 8088
spring:
    datasource:
        #存储的数据库账号
        username: root
        #存储的数据库账号
        password: 123456
        #存储的数据库地址 localhost 为ip地址 3306为数据库端口 tianailu为数据库库名
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
    scan:
        base-packages: com.asura.dubboproduce
    protocol:
        name: dubbo
        port: 12345
    registry:
        address: zookeeper://localhost:2181
    metadata-report:
        address: zookeeper://localhost:2181
    application:
        id: asura-provider
        qosEnable: true
        qosPort: 22222
        qosAcceptForeignIp: true
        qos-enable-compatible: true
        qos-host-compatible: localhost
        qos-port-compatible: 22222
        qos-accept-foreign-ip-compatible: true
        qos-host: localhost

redis:
    cache:
        database: 0
    session:
        database: 1
    host: 127.0.0.1
    port: 6379
    password: redis_123456789
    timeout: 2000
    lettuce:
        pool:
            max-active: 8
            max-wait: 5000
            max-idle: 4
            min-idle: 0
        shutdown-timeout: 5000

hmily:
    support:
        rpc:
            annotation: true