server:
  #部署的端口号
    port: 8080
    servlet:
        context-path: /
spring:
    datasource:
        #存储的数据库账号
        username: root
        #存储的数据库账号
        password: 123456
        #存储的数据库地址 localhost 为ip地址 3306为数据库端口 test为数据库库名
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        useGlobalDataSourceStat: true
        druid:
            # 初始连接
            initialSize: 10
            # 最大连接
            maxActive: 20
            # 最小连接
            minIdle: 5
            # 最大等待连接时间ms
            maxWait: 60000
            # PSCache对支持游标的数据库性能提升巨大 mysql建议关闭
            poolPreparedStatements: false
            maxOpenPreparedStatements: 0
            # 检查连接是否有效的sql 要求查询语句
            validationQuery: select 1
            validationQueryTimeout: 5
            testOnBorrow: false
            testWhileIdle: true
            filters: stat,wall,log4j
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
