server:
    #部署的端口号
    port: 8088
    servlet:
        context-path: /
spring:
    datasource:
        #存储的数据库账号
        username: root
        #存储的数据库账号
        password: 123456
        #存储的数据库地址 localhost 为ip地址 3306为数据库端口 tianailu为数据库库名
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    cache:
        type: redis
    redis:
        cluster:
            nodes:
                - 127.0.0.1:6379
                - 127.0.0.1:6380
                - 127.0.0.1:6381
                - 127.0.0.1:6382
            max-redirects: 3  # 获取失败 最大重定向次数
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-idle: 10    # 连接池中的最大空闲连接
            max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
            min-idle:  5     # 连接池中的最小空闲连接
        timeout: 15000  # 连接超时时长（毫秒）