server:
    #部署的端口号
    port: 8089
    servlet:
        context-path: /
spring:
    shardingsphere:
        datasource:
            names: master,slave2,slave3
            master:
                url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            slave2:
                url: jdbc:mysql://localhost:3326/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            slave3:
                url: jdbc:mysql://localhost:3336/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
        rules:
            readwrite-splitting:
                load-balancers:
                    masterbalancer:
                        type: ROUND_ROBIN
                data-sources:
                    master:
                        write-data-source-name: master
                        read-data-source-names: master,slave2,slave3
                        load-balancer-name: masterbalancer
        props:
            sql:
                # 显示sql，默认为false
                show: true