server:
    #部署的端口号
    port: 8099
    servlet:
        context-path: /
spring:
    main:
        allow-bean-definition-overriding: true
    shardingsphere:
        datasource:
            names: ds0,ds1,ds2
            ds0:
                url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            ds1:
                url: jdbc:mysql://localhost:3326/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            ds2:
                url: jdbc:mysql://localhost:3336/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
        sharding:
            default-database-strategy:
                inline:
                    sharding-column: user_id
                    algorithm-expression: ds$->{user_id % 3}
            tables:
                share_order:
                    actual-data-nodes: ds$->{0..2}.share_order_$->{0..15}
                    table-strategy:
                        inline:
                            sharding-column: id
                            algorithm-expression: share_order_$->{id % 16}
                    key-generator:
                        column: id
                        type: SNOWFLAKE
        props:
            sql:
                # 显示sql，默认为false
                show: true
