server:
    #部署的端口号
    port: 8089
    servlet:
        context-path: /
spring:
    main:
        allow-bean-definition-overriding: true
    shardingsphere:
        datasource:
            names: ds1,ds2,ds3
            ds1:
                url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            ds2:
                url: jdbc:mysql://localhost:3326/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
            ds3:
                url: jdbc:mysql://localhost:3336/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC
                username: root
                password: 123456
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
        sharding:
            default-database-strategy:
                inline:
                    sharding-column: user_id
                    algorithm-expression: ds$->{user_id % 3}
            tables:
                asura_order:
                    actual-data-nodes: ds$->{1..3}.asura_order_$->{1..16}
                    table-strategy:
                        inline:
                            sharding-column: id
                            algorithm-expression: asura_order_$->{id % 16}
                    key-generator:
                        column: id
                        type: SNOWFLAKE
        masterslave:
            name: ms
            master-data-source-name: ds1
            slave-data-source-names: ds2,ds3
        props:
            sql:
                # 显示sql，默认为false
                show: true
