
com:
  asura:
    student:
      id: 1
      name: stu1
    xlass:
      students: [{"id": "2", "name": "stu2"}, {"id": "3", "name": "stu3"}]
    school:
      xlass: {"students": [{"id": "4", "name": "stu2"}, {"id": "5", "name": "stu3"}]}
      student: {"id": "9", "name": "stu9"}
